CG/CG.Web/Models/ViewModels/TagViewModel.cs
using AutoMapper;
using CG.Infrastructure.Mappings;
using CG.Models;

namespace CG.Web.Models.ViewModels
{
    public class TagViewModel : IMapFrom<Tag>, IHaveCustomMappings
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public void CreateMappings(IConfiguration configuration)
        {
            configuration.CreateMap<Tag, TagViewModel>()
                .ReverseMap();
        }
    }
}

CG/CG.Web/Controllers/TagsController.cs
using System.Linq;
using System.Web.Mvc;
using AutoMapper.QueryableExtensions;
using CG.Data.UoW;
using CG.Web.Models.ViewModels;

namespace CG.Web.Controllers
{
    using System;

    using AutoMapper;

    using CG.Models;
    using CG.Web.Models.BindingModel;

    [Authorize]
    public class TagsController : BaseController
    {
        public TagsController(ICGData data) : base(data)
        {
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult All()
        {
            var tags =
                this.Data.Tags.All()
                    .OrderByDescending(t => t.CreatedOn)
                    .ProjectTo<TagViewModel>()
                    .ToList();

            return this.View(tags);
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult GetTagCodeGists(int id)
        {
            var tag = this.FindTagById(id);
            if (tag == null)
            {
                return this.HttpNotFound("404 Not found");
            }

            var tagCodeGists =
                tag.CodeGists.AsQueryable()
                   .ProjectTo<CodeGistViewModel>()
                   .ToList();
            return this.View(tagCodeGists);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return this.View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(TagBindingModel model)
        {
            if (this.ModelState.IsValid)
            {
                var tag = Mapper.Map<TagBindingModel, Tag>(model);
                this.Data.Tags.Add(tag);
                this.Data.SaveChanges();
            }
            return this.View(model);
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            var tag = this.FindTagById(id);
            if (tag == null)
            {
                return this.HttpNotFound("404 Not found");
            }

            tag.IsDeleted = true;
            tag.DeletedOn = DateTime.Now;
            this.Data.Tags.Update(tag);
            this.Data.SaveChanges();
            return this.RedirectToAction("All");
        }

        private Tag FindTagById(int tagId)
        {
            return this.Data.Tags.All().FirstOrDefault(t => t.Id == tagId);
        }
    }
}

CG/CG.Web/Views/Tags/All.cshtml
@model IEnumerable<CG.Web.Models.ViewModels.TagViewModel>
@{
    ViewBag.Title = "All";
}

<h2>All</h2>

<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="col-md-4">
            @Html.DisplayFor(x => x, "TagViewModel")
        </div>
    </div>
</div>

CG/CG.Web/Views/Tags/Create.cshtml
@model CG.Web.Models.BindingModel.TagBindingModel
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        @using (Html.BeginForm("Create", "Tags", FormMethod.Post, new{@class="form-horizontal"}))
        {
            @Html.AntiForgeryToken()
            @Html.LabelFor(x=>x.Title, new {@class="label label-info"})
            <br/>
            @Html.EditorFor(x=>x.Title, new {@class="form-control"})
    <br />
    <br />
            <input type="submit" value="Create" class="btn btn-primary"/>
        }
    </div>
</div>

CG/CG.Web/Views/Tags/GetTagCodeGists.cshtml
@model IEnumerable<CG.Web.Models.ViewModels.CodeGistViewModel>
@{
    ViewBag.Title = "GetTagCodeGists";
}

<h2>GetTagCodeGists</h2>

@Html.DisplayFor(x => x, "CodeGistViewModel")